apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub
  namespace: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "secrets", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub
  namespace: development
subjects:
  - kind: ServiceAccount
    name: jupyterhub
    namespace: development
roleRef:
  kind: Role
  name: jupyterhub
  apiGroup: rbac.authorization.k8s.io
