apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform

resources:
  - dask-scheduler.yaml
  - dask-worker.yaml
  - ray-cluster.yaml

commonLabels:
  app.kubernetes.io/component: distributed-compute
  app.kubernetes.io/part-of: rpi-k8s-platform
