# =============================================================================
# PostgreSQL Credentials for BentoML
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: yatai-postgresql
  namespace: ml-platform
type: Opaque
stringData:
  host: postgresql.data-services.svc.cluster.local
  port: "5432"
  database: bentoml
  user: bentoml
  password: bentoml123
