apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: rpi-k8s-platform
